### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by schwamic** [sanity-io/sanity-template-nextjs-landing-pages#13]
**Describe the bug**

Hey, I implemented `link`, `internalLink` and `portableText` like described in your example: [sanity-template-nextjs-landing-pages](https://github.com/sanity-io/sanity-template-nextjs-landing-pages/tree/master/template/studio/schemas).

If I edit the following in studio:
<img width="543" alt="Screenshot 2020-03-26 at 15 54 27" src="https://user-images.githubusercontent.com/18497277/77660846-1bb8a380-6f7a-11ea-9eb0-0f7398299237.png">

I get this back:
```
_key: "5c69a0901ef51"
_type: "span"
marks: Array(1)
0: "5da972bc4fca"
length: 1
__proto__: Array(0)
text: "mail@example.org"
__proto__: Object
```

**Expected behaviour**

I expected to get something of type `url` with a `href` prop and not a type `span` with a `text` prop. That makes it very difficult to render the data correctly in my app. I also tried to render the data by `marks` prop, but this number changes sometimes.

**Which versions of Sanity are you using?**

```
"@sanity/base": "^1.149.5",
"@sanity/components": "^1.149.5",
"@sanity/core": "^1.149.4",
"@sanity/default-layout": "^1.149.5",
"@sanity/default-login": "^1.149.0",
"@sanity/desk-tool": "^1.149.5",
"@sanity/vision": "^1.149.0",
```

It is also possible that I have forgotten a step, but maybe it is also a bug.

**Comment by schwamic** [comment]
It works now, but it took me a while to figure it out. Maybe you could add more documentation for sanity-io/block-content-to-react library, which describes how to use serializers e.g. types, marks, list, listItem with custom react components.

**Comment by mikeyrayvon** [comment]
This article may be useful for you https://www.sanity.io/guides/portable-text-internal-and-external-links#render-the-links-with-react-b14f77c2e796
